# Generated by Django 3.1.6 on 2021-05-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(choices=[('SU', 'Student'), ('NS', 'Non Student')], max_length=2)),
                ('t_name', models.CharField(max_length=60)),
                ('t_surname', models.CharField(max_length=60)),
                ('t_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'verbose_name': 'Проживающий',
                'verbose_name_plural': 'Проживающие',
            },
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежития',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.IntegerField()),
                ('r_floor', models.IntegerField()),
                ('r_capacity', models.IntegerField(default=2)),
                ('r_type', models.CharField(choices=[('SU', 'Student'), ('NS', 'Non Student')], max_length=2)),
                ('dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents_app.dorm')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_order_no', models.IntegerField()),
                ('r_date', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents_app.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents_app.application')),
            ],
            options={
                'verbose_name_plural': 'Заселения',
            },
        ),
    ]
