# Generated by Django 3.2.3 on 2021-06-02 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(choices=[('SU', 'Обучающийся'), ('NS', 'Не обучающийся')], max_length=2, verbose_name='Обучающийся/Иное')),
                ('t_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('t_surname', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('t_sex', models.CharField(choices=[('M', 'Муж.'), ('F', 'Жен.')], max_length=1, verbose_name='М/Ж')),
            ],
            options={
                'verbose_name': 'Проживающий',
                'verbose_name_plural': 'Проживающие',
            },
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50, verbose_name='Наиминование')),
                ('capacity', models.IntegerField(verbose_name='Общее количество мест')),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежития',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.IntegerField(verbose_name='Номер')),
                ('r_floor', models.IntegerField(verbose_name='Этаж')),
                ('r_capacity', models.IntegerField(default=2, verbose_name='Мест')),
                ('r_type', models.CharField(choices=[('SU', 'Обучающийся'), ('NS', 'Не обучающийся')], max_length=2, verbose_name='Студенческое/Иное')),
                ('dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents_app.dorm', verbose_name='Общежитие')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_order_no', models.IntegerField(verbose_name='Приказ о заселении')),
                ('r_date', models.DateField(verbose_name='Дата приказа о заселении')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents_app.room', verbose_name='Комната')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents_app.application', verbose_name='Проживающий')),
            ],
            options={
                'verbose_name': 'Заселение',
                'verbose_name_plural': 'Заселения',
            },
        ),
    ]
