# Generated by Django 3.2.6 on 2021-08-09 14:28

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import users_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('uin', models.CharField(max_length=12, null=True, unique=True, validators=[users_app.models.only_int, django.core.validators.MinLengthValidator(12)])),
                ('status', models.CharField(choices=[('студент', 'Студент'), ('админ', 'Админ')], default='студент', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('birthplace', models.CharField(blank=True, default='', max_length=255)),
                ('social_status', models.CharField(blank=True, default='', max_length=255)),
                ('receipt_date', models.DateField(null=True)),
                ('gpa', models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(4)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/users/avatar')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
