# Generated by Django 3.2.6 on 2021-08-09 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0002_auto_20210809_1452'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='edProgram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='oil_grants.edprogram'),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=140, unique=True, verbose_name='Email адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gpa',
            field=models.FloatField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/avatar', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='users',
            name='social_status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Социальный статус'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('студент', 'Студент'), ('админ', 'Админ')], default='студент', max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='uin',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[users_app.models.only_int, django.core.validators.MinLengthValidator(12)], verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
