# Generated by Django 3.2.6 on 2021-08-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0002_auto_20210809_1452'),
        ('users_app', '0002_auto_20210809_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='edProgram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='oil_grants.edprogram'),
        ),
        migrations.AlterField(
            model_name='users',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
