# Generated by Django 3.2.6 on 2021-08-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oil_grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Обучающийся'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL, verbose_name='Обучающийся'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
