# Generated by Django 3.2.6 on 2021-08-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0003_auto_20210811_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions',
            name='ed_program',
        ),
    ]
