# Generated by Django 3.2.6 on 2021-08-11 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oil_grants', '0004_remove_competitions_ed_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('essay', models.PositiveIntegerField(blank=True, null=True, verbose_name='Балл за эссе')),
                ('computerTest', models.PositiveIntegerField(blank=True, null=True, verbose_name='Балл компьютерного теста')),
                ('status', models.CharField(choices=[('REC', 'Получена'), ('REV', 'Рассматривается'), ('RET', 'Отправлена на доработку'), ('ACC', 'Одобрена'), ('REJ', 'Отклонена')], max_length=3, verbose_name='Статус заявки')),
                ('description', models.CharField(blank=True, max_length=1500, verbose_name='Описание')),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка на конкурс',
                'verbose_name_plural': 'Заявки на конкурсы',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('contact_num', models.CharField(max_length=15, verbose_name='Контактный номер')),
                ('description', models.CharField(blank=True, max_length=1500, verbose_name='Описание')),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Компания недропользователь',
                'verbose_name_plural': 'Компании недропользователи',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateField(verbose_name='Дата заключения')),
                ('duration', models.CharField(choices=[('YR', 'Год'), ('SM', 'Семестр')], max_length=3, verbose_name='Период оплаты учебы')),
                ('fee', models.IntegerField(verbose_name='Сумма гранта')),
                ('contractNo', models.CharField(max_length=15, verbose_name='Номер договора')),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oil_grants.company', verbose_name='Компания спонсор')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Присвоенный грант',
                'verbose_name_plural': 'Списки присвоенных грантов',
            },
        ),
        migrations.RemoveField(
            model_name='participants',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='student',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='student',
        ),
        migrations.AddField(
            model_name='competitions',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='date_of_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода объявления'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='end',
            field=models.DateField(verbose_name='Дата начала приема заявок'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='start',
            field=models.DateField(verbose_name='Дата начала приема заявок'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='status',
            field=models.CharField(choices=[("didn't start", 'Не начался'), ('goes on', 'Продолжается'), ('ended', 'Завершился')], default="didn't start", max_length=15, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='applications',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oil_grants.competitions'),
        ),
        migrations.AddField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='oil_grants.company', verbose_name='Компания недропользователь'),
        ),
        migrations.DeleteModel(
            name='OilCompany',
        ),
    ]
