# Generated by Django 3.2.6 on 2021-08-11 05:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0005_auto_20210811_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
