# Generated by Django 3.2.6 on 2021-08-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oil_grants', '0007_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('REC', 'Получена'), ('REV', 'Рассматривается'), ('RET', 'Отправлена на доработку'), ('ACC', 'Одобрена'), ('REJ', 'Отклонена')], default='REC', max_length=3, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
