# Generated by Django 3.2.6 on 2021-08-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0008_auto_20210811_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='oil_grants.contract'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='oil_grants.competitions'),
        ),
    ]
