# Generated by Django 3.2.6 on 2021-08-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0010_alter_competitions_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edprogram',
            name='p_name',
            field=models.CharField(max_length=255, verbose_name='Наименование ОП'),
        ),
    ]
