# Generated by Django 3.2.6 on 2021-08-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0012_auto_20210813_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCompetitionNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_number', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'Использованные номера конкурсов',
            },
        ),
        migrations.AddField(
            model_name='competitions',
            name='competition_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
