# Generated by Django 3.2.6 on 2021-08-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0014_alter_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='oil_grants.contract'),
        ),
    ]
