# Generated by Django 3.2.6 on 2021-08-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil_grants', '0016_auto_20210819_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitions',
            options={'ordering': ['-date_of_add'], 'verbose_name': 'Конкурс', 'verbose_name_plural': 'Конкурсы'},
        ),
    ]
